# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymea/ui/MEAToolsMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.directoryLabel = QtWidgets.QLabel(self.tab)
        self.directoryLabel.setText("")
        self.directoryLabel.setObjectName("directoryLabel")
        self.horizontalLayout.addWidget(self.directoryLabel)
        self.browseButton = QtWidgets.QPushButton(self.tab)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filenameListWidget = QtWidgets.QListWidget(self.tab)
        self.filenameListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.filenameListWidget.setObjectName("filenameListWidget")
        self.horizontalLayout_4.addWidget(self.filenameListWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectAllButton = QtWidgets.QPushButton(self.tab)
        self.selectAllButton.setObjectName("selectAllButton")
        self.verticalLayout.addWidget(self.selectAllButton)
        self.selectNoneButton = QtWidgets.QPushButton(self.tab)
        self.selectNoneButton.setObjectName("selectNoneButton")
        self.verticalLayout.addWidget(self.selectNoneButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.thresholdSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.thresholdSpinBox.setMinimum(1.0)
        self.thresholdSpinBox.setMaximum(100.0)
        self.thresholdSpinBox.setProperty("value", 6.0)
        self.thresholdSpinBox.setObjectName("thresholdSpinBox")
        self.horizontalLayout_3.addWidget(self.thresholdSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.spikeSortCheckBox = QtWidgets.QCheckBox(self.tab)
        self.spikeSortCheckBox.setChecked(True)
        self.spikeSortCheckBox.setObjectName("spikeSortCheckBox")
        self.verticalLayout.addWidget(self.spikeSortCheckBox)
        self.tagPropagationCheckBox = QtWidgets.QCheckBox(self.tab)
        self.tagPropagationCheckBox.setObjectName("tagPropagationCheckBox")
        self.verticalLayout.addWidget(self.tagPropagationCheckBox)
        self.negativePeakOnlyCheckBox = QtWidgets.QCheckBox(self.tab)
        self.negativePeakOnlyCheckBox.setObjectName("negativePeakOnlyCheckBox")
        self.verticalLayout.addWidget(self.negativePeakOnlyCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.convertButton = QtWidgets.QPushButton(self.tab)
        self.convertButton.setObjectName("convertButton")
        self.verticalLayout.addWidget(self.convertButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logTextEdit = QtWidgets.QTextEdit(self.tab_2)
        self.logTextEdit.setEnabled(True)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_3.addWidget(self.logTextEdit)
        self.tabWidget.addTab(self.tab_2, "Log")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.selectAllButton.setText(_translate("MainWindow", "Select All"))
        self.selectNoneButton.setText(_translate("MainWindow", "Select None"))
        self.label.setText(_translate("MainWindow", "Threshold"))
        self.spikeSortCheckBox.setText(_translate("MainWindow", "Sort Spikes"))
        self.tagPropagationCheckBox.setText(_translate("MainWindow", "Tag Propagation Signals"))
        self.negativePeakOnlyCheckBox.setText(_translate("MainWindow", " Negative Peaks Only"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Files"))

